config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'home#index'
  resources :livres do
    resources :emprunts
      resources :likes, only: [:create, :destroy]
  end
  resources :users
  get 'emprunts' => 'emprunts#index', as: :emprunts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emprunt.rb
class Emprunt < ApplicationRecord
  belongs_to :user
  belongs_to :livre
  # validates :note, numericality: { greater_than: 0 }
  # validates :note, numericality: { less_than: 6 }
  validates :date_debut, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :livre
  belongs_to :user
end

app/models/livre.rb
class Livre < ApplicationRecord
  belongs_to :user
  has_many :emprunts
  has_many :likes, dependent: :destroy
  mount_uploader :video, VideoUploader
  validates :user, :titre, presence: true
  scope :by_score, -> { joins(:emprunts).where("emprunts.note > 0").group("livres.id").order("AVG(emprunts.note) DESC")}

  include PgSearch
  pg_search_scope :search_livres,
    against: [ :titre, :auteur ],
    associated_against: {
      user: [ :prenom, :nom ]
    },
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

  def titre_auteur
    "#{titre} - #{auteur}"
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :livres
  has_many :emprunts
  has_many :likes, dependent: :destroy
  validate :email_domain
  mount_uploader :photo, VideoUploader
# Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def prenom_nom
  "#{prenom} #{nom}"
  end

  def email_domain
    domain = email.split("@").last
    if !email.blank?
      errors.add(:email, "Invalid Domain") if domain != "twelve-consulting.com"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/emprunts_controller.rb
class EmpruntsController < ApplicationController

  def index
    if params[:livre_id]
      @emprunts = Livre.find(params[:livre_id]).emprunts
    else
      @emprunts = Emprunt.all
    end
  end

  def show
    @livre = Livre.find(params[:livre_id])
    @emprunt = Emprunt.find(params[:id])
  end

  def new
    @livre = Livre.find(params[:livre_id])
    @emprunt = Emprunt.new
    @emprunt.user = current_user
    @emprunt.livre = @livre
    @emprunt.date_debut = DateTime.now
  end

  def create
    @emprunt = Emprunt.new(emprunt_params)
    @emprunt.livre = Livre.find(params[:livre_id])
    if @emprunt.save
      @emprunt.save!
      if @emprunt.livre.user.livre_emprunte == true
        EmpruntMailer.emprunt(@emprunt).deliver_now
      end
      redirect_to livre_path(@emprunt.livre)
    else
      render :edit
    end
  end

  def edit
    @livre = Livre.find(params[:livre_id])
    @emprunt = Emprunt.find(params[:id])
  end

  def update
    @livre = Livre.find(params[:livre_id])
    @emprunt = Emprunt.find(params[:id])
    if @emprunt.update(emprunt_params)
      if @emprunt.note != nil
        if @emprunt.livre.user.livre_rendu == true
          EmpruntMailer.rendu(@emprunt).deliver_now
        end
      end
      redirect_to livre_path(@emprunt.livre)
    else
     render :edit
    end
  end

  def destroy
    @emprunt = Emprunt.find(params[:id])
    @emprunt.destroy
    redirect_to livres_path
  end

end

private

def emprunt_params
  params.require(:emprunt).permit(:user_id, :date_debut, :date_fin, :avis, :note, :livre_id)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @livres = Livre.by_score.limit(3)
    @emprunts = Emprunt.where("note > '0'").order({updated_at: :desc}).limit(3)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :find_post
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
    else
      @livre.likes.create(user_id: current_user.id)
      redirect_to request.referer
    end
  end

  def destroy
    @like.destroy
    redirect_to request.referer
  end

  private

  def find_post
    @livre = Livre.find(params[:livre_id])
  end

  def find_like
     @like = @livre.likes.find(params[:id])
  end

  def already_liked?
    Like.where(user_id: current_user.id, livre_id:
    params[:livre_id]).exists?
  end

end

app/controllers/livres_controller.rb
class LivresController < ApplicationController
  def index
    if params[:query].present?
      @livres = Livre.search_livres(params['query'])
    else
      @livres = Livre.all
    end
  end

  def show
    @livre = Livre.find(params[:id])
  end

  def new
    @livre = Livre.new
    @livre.user = current_user
  end

  def create
    @livre = Livre.new(livre_params)
    @livre.save!
    redirect_to livre_path(@livre)
  end

  def edit
    @livre = Livre.find(params[:id])
  end

  def update
    @livre = Livre.find(params[:id])
      if @livre.update(livre_params)
        redirect_to livre_path(@livre)
      else
       render :edit
      end
  end

  private

  def livre_params
    params.require(:livre).permit(:titre, :auteur, :video, :description, :user_id, :pochette)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    "/users/#{current_user.id}/edit" # Or :prefix_to_your_route
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to edit_user_path, notice: 'Profil was successfully updated.'
      else
       render :edit
      end
  end

  private

  def user_params
      params.require(:user).permit(:prenom, :nom, :email, :photo, :livre_emprunte, :livre_rendu, :notif_hebdo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/emprunts/edit.html.erb
<div class="banner">
  <h1>Mise à jour </h1>
</div>
<div class="container">
  <%= simple_form_for [@livre, @emprunt] do |f| %>
    <div class="formulaire">
      <%= f.association :user, label_method: :prenom_nom %>
      <%= f.association :livre, label_method: :titre_auteur %>
      <%= f.input :date_debut, as: :date, html5: true %>
      <%= f.input :date_fin, as: :date, html5: true %>
      <%= f.input :note, as: :hidden %>
      <%= f.label :note, "Note" %>
      <div class="notation">
        <i class="fas fa-star clickstar" data-star="1"></i>
        <i class="fas fa-star clickstar" data-star="2"></i>
        <i class="fas fa-star clickstar" data-star="3"></i>
        <i class="fas fa-star clickstar" data-star="4"></i>
        <i class="fas fa-star clickstar" data-star="5"></i>
      </div>
      <%= f.input :avis %>
      <%= f.submit "Enregistrer", class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/emprunts/index.html.erb
<div class="banner">
  <h1>Liste des emprunts </h1>
</div>
<div class="container">
  <% @emprunts.each do |emprunt| %>
    <div class="emprunts">
      <div class="row">
        <div class="col-xs-3 vcenter">
          <% if emprunt.user.photo.present? %>
            <%= cl_image_tag emprunt.user.photo, class: "avatar" %><br>
            <%= emprunt.user.prenom %> <%= emprunt.user.nom %>
          <% else %>
            <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "avatar") %><br>
            <%= emprunt.user.prenom %> <%= emprunt.user.nom %>
          <% end %>
        </div>
        <div class="col-xs-6 vcenter">
          <% if emprunt.user.prenom.present? %>
            <h3><%= emprunt.id %> - <%= emprunt.livre.titre %></h3>
            <p><strong>Date d'emprunt :</strong> <%= emprunt.date_debut.strftime("%d/%m/%Y") %></p>
            <% if emprunt.date_fin.present?  %>
              <p><strong>Rendu le :</strong> <%= emprunt.date_fin.strftime("%d/%m/%Y") %></p>
            <% else %>
              <p><strong>Livre pas encore rendu</strong></p>
            <% end %>
          <% else %>
            <h2><%= emprunt.user.email %></h2>
          <% end %>
        </div>
        <div class="col-xs-2 vcenter">
          <% if emprunt.livre.pochette.present? %>
            <%= cl_image_tag emprunt.livre.pochette, class: "pochette-mini" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/emprunts/new.html.erb
<div class="banner">
  <h1>Emprunter : <%= @livre.titre %></h1>
</div>
<div class="container">
  <%= simple_form_for [@livre, @emprunt] do |f| %>
    <div class="formulaire">
      <%= f.label :user, "Twelveur" %>
      <%= f.association :user, label_method: :prenom_nom, label: false %>
      <%= f.association :livre, label_method: :titre_auteur %>
      <%= f.label :date_debut, "Date d'emprunt" %>
      <%= f.input :date_debut, as: :date, html5: true, label: false %>
      <%= f.label :date_fin, "Fin de l'emprunt" %>
      <%= f.input :date_fin, as: :date, html5: true, label: false %>
      <%= f.label :note, "Note" %>
      <%= f.input :note, as: :hidden %>
      <div class="notation">
        <i class="fas fa-star clickstar" data-star="1"></i>
        <i class="fas fa-star clickstar" data-star="2"></i>
        <i class="fas fa-star clickstar" data-star="3"></i>
        <i class="fas fa-star clickstar" data-star="4"></i>
        <i class="fas fa-star clickstar" data-star="5"></i>
      </div>
      <%= f.input :avis %>
      <%= f.submit "Enregistrer", class: "btn btn-success"%>
    </div>
  <% end %>
</div>

app/views/emprunts/show.html.erb
<div class="banner-livre">
  <div class="pochette">
    <%= link_to livre_path(@livre), class:"grey-link" do %>
      <%= cl_image_tag @livre.pochette %>
    <% end %>
  </div>
  <div class="infos">
    <%= link_to livre_path(@livre), class:"grey-link" do %>
      <h1><%= @livre.titre %> </h1>
    <% end %>
    <h2>Lu par <%= @emprunt.user.prenom %>
      <%= link_to edit_livre_emprunt_path(@livre, @emprunt), class:"white-link" do %>
        <i class="fas fa-edit"></i></h2>
      <% end %>
  </div>
</div>
<div class="container">
  <p><strong>Date d'emprunt : </strong><%= @emprunt.date_debut %></p>
  <p><strong>Date de rendu : </strong><%= @emprunt.date_fin %></p>
  <p><strong>Avis : </strong><%= @emprunt.avis %></p>
  <p><strong>Note : </strong><%= @emprunt.note %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>12 library</title>
    <%= favicon_link_tag "symbol.ico" %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/livres/index.html.erb
<div class="home-banner">
  <h1>Bienvenue les lecteurs ! </h1>
  <form action="/livres" method="get" class="searchbar">
    <input type="text" name="query" placeholder="Rechercher un livre !" class="form-control">
    <input type="submit" class= "btn btn-success" value="Ok">
  </form>
</div>
<div class="container">
  <div class="row">
    <% @livres.each do |livre| %>
      <div class="col-xs-12 col-md-6 col-sm-6 col-lg-4">
        <div class="card">
          <div class="card-top">
            <% if livre.user.prenom.present? %>
              <div class="card-category"><%= livre.user.prenom %></div>
            <% else %>
              <div class="card-category">12eur inconnu</div>
            <% end %>
            <div class="card-description">
              <h2><%= livre.titre %> </h2>
              <p><%= livre.auteur %></p>
            </div>
            <% if livre.user.photo.present? %>
              <%= cl_image_tag livre.user.photo, class: "card-user" %>
            <% else %>
              <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "card-user") %>
            <% end %>
          </div>
          <div class="card-bottom">
            <% if livre.emprunts.sum(:note) > 0 %>
              <p><%= livre.emprunts.average(:note).round(1) %>/5 (<%= livre.emprunts.count(:note) %> avis)</p>
              <% if Like.where(user_id: current_user.id, livre_id: livre.id).exists? %>
                <% pre_like = livre.likes.find { |like| like.user_id == current_user.id} %>
                <%= link_to livre_like_path(livre, pre_like), method: :delete do %>
                  <i class="fas fa-list-alt likeButton" data-like="true"></i></h2>
                <% end %>
              <% else %>
                <%= link_to livre_likes_path(livre), method: :post, params: { livre_id: livre.id } do %>
                  <i class="fas fa-list-alt" data-like="false"></i></h2>
                <% end %>
              <% end %>
            <% else %>
              <p>Pas encore de note</p>
              <% if Like.where(user_id: current_user.id, livre_id: livre.id).exists? %>
                <% pre_like = livre.likes.find { |like| like.user_id == current_user.id} %>
                <%= link_to livre_like_path(livre, pre_like), method: :delete do %>
                  <i class="fas fa-list-alt likeButton" data-like="true"></i></h2>
                <% end %>
              <% else %>
                  <%= link_to livre_likes_path(livre), method: :post, params: { livre_id: livre.id } do %>
                    <i class="fas fa-list-alt" data-like="false"></i></h2>
                  <% end %>
              <% end %>
            <% end %>
          </div>
          <%= link_to "", livre_path(livre), class: 'card-link' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/livres/show.html.erb
<div class="banner-livre">
  <div class="banner-container">
    <div class="pochette">
      <%= cl_image_tag @livre.pochette %>
    </div>
    <div class="infos">
      <h1 id="title"><%= @livre.titre %> </h1>
      <h2 id="propose-par">Proposé par <%= link_to @livre.user.prenom, user_path(@livre.user), class: "h2" %>
      <% if current_user == @livre.user %>
        <%= link_to edit_livre_path(@livre), id:"white-link" do %>
          <i class="fas fa-edit"></i></h2>
        <% end %>
      <% end %>
    </div>
    <div class="moyenne">
      <% if @livre.emprunts.sum(:note) > 0 %>
        <h1 id="average"><%= @livre.emprunts.average(:note).round(1) %> /5</h1>
      <% else %>
        <h2>0 note</h2>
      <% end %>
    </div>
  </div>
</div>
<div class="menu">
  <%= link_to "Emprunter", new_livre_emprunt_path(@livre), class: "btn btn-success btn-show" %>
  <% if Like.where(user_id: current_user.id, livre_id: @livre.id).exists? %>
    <% pre_like = @livre.likes.find { |like| like.user_id == current_user.id} %>
    <%= link_to livre_like_path(@livre, pre_like), method: :delete do %>
      <i class="fas fa-list-alt likeButton" data-like="true"></i></h2>
    <% end %>
  <% else %>
      <%= link_to livre_likes_path(@livre), method: :post, params: { livre_id: @livre.id } do %>
        <i class="fas fa-list-alt" data-like="false"></i></h2>
      <% end %>
  <% end %>
</div>
<div class="container">
  <div class="row">
    <div class="col-lg-6 col-xs-12">
       <h2>L'avis de <strong><%= @livre.user.prenom %></strong> </h2>
       <video width="300" height="500" controls><source src="<%= @livre.video %>" type="video/mp4"></video>
    </div>
    <div class="col-lg-6 col-xs-12">
      <h2>Un livre de <strong><%= @livre.auteur %></strong> </h2>
      <p class="description"><%= @livre.description %></p>
    </div>
  </div>
  <% if @livre.emprunts.count > 0 %>
    <div class="emprunt-display">
      <h2>Emprunts et avis</h2>
      <% @livre.emprunts.each do |emprunt| %>
        <div class="emprunt">
          <div class="entete">
            <div class="avatar-emprunteur">
              <% if emprunt.user.photo.present? %>
                <%= link_to user_path(emprunt.user), id:"white-link" do %>
                  <%= cl_image_tag emprunt.user.photo %>
                <% end %>
              <% else %>
                <%= link_to user_path(emprunt.user), id:"white-link" do %>
                  <%= image_tag('https://www.limestone.edu/sites/default/files/user.png') %>
                <% end %>
              <% end %>
            </div>
            <div class="detail-emprunt">
              <p id="titre-avis"><strong><%= emprunt.user.prenom %></strong> (du <%= emprunt.date_debut.strftime("%d/%m/%Y") %> <%=emprunt.date_fin.present? ? "au #{emprunt.date_fin.strftime("%d/%m/%Y")}" : " - Pas encore rendu" %>)</p>
              <% if emprunt.note != nil %>
                <% emprunt.note.times do  %>
                  <i class="fas fa-star"></i>
                <% end %>
              <% end %>
            </div>
            <div class="edit-avis">
              <% if current_user == emprunt.user %>
                <%= link_to edit_livre_emprunt_path(@livre, emprunt), class:"grey-link" do %>
                  <i class="fas fa-edit"></i></h2>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="avis-emprunteur">
            <p><%= emprunt.avis %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "symbol.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Home", livres_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Bibliothèque", livres_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Ajouter un livre", new_livre_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Twelveurs", users_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo, width: 100, crop: :fill, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <% else %>
              <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown") %>
            <%end%>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home", livres_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% if current_user.present? %>
          <li><%= link_to "Profil", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
        <li><%= link_to "Bibliothèque", livres_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Ajouter un livre", new_livre_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Twelveurs", users_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <li><%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="banner">
  <h1>Le gang des lecteurs </h1>
</div>
<div class="container">
  <% @users.each do |user| %>
    <div class="user-list">
      <div class="row">
        <div class="col-xs-3">
          <% if user.photo.present? %>
            <%= cl_image_tag user.photo, class: "avatar" %>
          <% else %>
            <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "avatar") %>
          <% end %>
        </div>
        <div class="col-xs-7">
          <% if user.prenom.present? %>
            <h2><%= user.prenom %> <%= user.nom %></h2>
          <% else %>
            <h2><%= user.email %></h2>
          <% end %>
        </div>
        <div class="col-xs-2">
          <%= link_to user_path(user) do %>
            <i class="fas fa-arrow-circle-right"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="banner">
  <div class="user-profile">
    <div class="user-photo">
      <% if @user.photo.present? %>
        <%= cl_image_tag @user.photo, class: "avatar" %>
      <% else %>
        <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "avatar") %>
      <% end %>
    </div>
    <div class="user-name">
      <% if @user.prenom.present? || @user.nom.present? %>
        <h1><%= @user.prenom %> <%= @user.nom %>
        <% if current_user == @user %>
          <%= link_to edit_user_path(@user), id:"white-link" do %>
            <i class="fas fa-edit"></i></h1>
          <% end %>
        <% end %>
      <% else %>
        <h1>12eur inconnu
        <%= link_to edit_user_path(@user), id:"white-link" do %>
          <i class="fas fa-edit"></i></h1>
        <% end %>
      <% end %>
    </div>
    <div class="user-update">
    </div>
  </div>
  <div class="menu">
    <i class="fas fa-book user-icons red"></i>
    <i class="fas fa-glasses user-icons"></i>
    <i class="fas fa-heart user-icons"></i>
    <i class="fas fa-envelope user-icons"></i>
  </div>
</div>
</div>
<div class="container">
  <div class="mes-livres">
    <h2>Mes livres</h2>
    <% @user.livres.each do |livre| %>
      <div class="card">
        <div class="card-top">
          <% if livre.user.prenom.present? %>
            <div class="card-category"><%= livre.user.prenom %></div>
          <% else %>
            <div class="card-category">12eur inconnu</div>
          <% end %>
          <div class="card-description">
            <h2><%= livre.titre %> </h2>
            <p><%= livre.auteur %></p>
          </div>
          <% if livre.user.photo.present? %>
            <%= cl_image_tag livre.user.photo, class: "card-user" %>
          <% else %>
            <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "card-user") %>
          <% end %>
          <%= link_to "", livre_path(livre), class: 'card-link' %>
        </div>
        <div class="card-bottom">
          <% if livre.emprunts.sum(:note) > 0 %>
            <p><%= livre.emprunts.average(:note).round(1) %>/5 (<%= livre.emprunts.count(:note) %> avis)</p>
          <% else %>
            <p>Pas encore de note</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="mes-emprunts hidden">
    <h2>Mes Emprunts</h2>
    <% @user.emprunts.each do |emprunt| %>
      <div class="card">
        <div class="card-top">
          <% if emprunt.livre.user.prenom.present? %>
            <div class="card-category"><%= emprunt.livre.user.prenom %></div>
          <% else %>
            <div class="card-category">12eur inconnu</div>
          <% end %>
          <div class="card-description">
            <h2><%= emprunt.livre.titre %> </h2>
            <p><%= emprunt.livre.auteur %></p>
          </div>
          <% if emprunt.livre.user.photo.present? %>
            <%= cl_image_tag emprunt.livre.user.photo, class: "card-user" %>
          <% else %>
            <%= image_tag('https://www.limestone.edu/sites/default/files/user.png', class: "card-user") %>
          <% end %>
          <%= link_to "", livre_path(emprunt.livre), class: 'card-link' %>
        </div>
        <div class="card-bottom">
          <% if emprunt.livre.emprunts.sum(:note) > 0 %>
            <p><%= emprunt.livre.emprunts.average(:note).round(1) %>/5 (<%= emprunt.livre.emprunts.count(:note) %> avis)</p>
          <% else %>
            <p>Pas encore de note</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="notifications hidden">
    <h2>Mes préférences de communication</h2>
    <p>Notification hebdomadaire des nouveaux livres
    <% if @user.notif_hebdo == true %>
      <i class="fas fa-check-circle"></i>
    <% else %>
      <i class="fas fa-minus-circle"></i>
    <% end %></p>
    <p>Notification lorsqu'un de mes livres est emprunté
    <% if @user.livre_emprunte == true %>
      <i class="fas fa-check-circle"></i>
    <% else %>
      <i class="fas fa-minus-circle"></i>
    <% end %></p>
    <p>Notification lorsqu'un de mes livres est rendu
    <% if @user.livre_rendu == true %>
      <i class="fas fa-check-circle"></i>
    <% else %>
      <i class="fas fa-minus-circle"></i>
    <% end %></p>
  </div>
  <div class="wishlist hidden">
    <h2>Ma wishlist</h2>
    <% @user.likes.each do |like| %>
      <div class="like">
        <div class="like-pochette">
          <% if like.livre.pochette.present? %>
            <%= cl_image_tag like.livre.pochette, class: "pochette" %>
          <% end %>
        </div>
        <div class="like-info">
          <h3> <%= like.livre.titre %></h3>
          <p>De : <%= like.livre.auteur %></p>
          <p>Proposé par : <%= like.livre.user.prenom %></p>
        </div>
        <div class="like-suppression">
          <%= link_to livre_like_path(like.livre, like), method: :delete do %>
            <i class="fas fa-trash-alt likeButton" data-like="true"></i></h2>
          <% end %>
        </div>
        <%= link_to "", livre_path(like.livre), class: 'like-link' %>
      </div>
    <% end %>
  </div>
</div>